name: CD
on: 
  push:
    branches:
      - master
jobs:
    name: "Deploy"
    runs-on: ubuntu-latest
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/develop.key
          chmod 600 ~/.ssh/develop.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/develop.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
     - name: Run Install & Build
        run: ssh deploy 'cd repos/Project09-C-Uber-Clone && git pull && cd client && npm ci && npm run build'
      - name: Reload PM2
        run: ssh deploy 'cd repos/Project09-C-Uber-Clone/server && npm ci && pm2 reload Project09-C-Uber-Clone'
